DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: rsmix_gdanet_run_1 
  LOSS_NAME: smooth
  MODEL_NAME: gdanet
  SEED: 1
  METRIC: acc
  TASK: cls
TRAIN:
  l2: 0.0
AUG:
  NAME: rsmix
  BETA: 1.
  PROB: 0.5