DATALOADER:
  batch_size: 40
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: cutmix_r_robustnet2_run_1_2
  LOSS_NAME: smooth
  MODEL_NAME: robustnet2
  SEED: 1
  TASK: cls
  OPTIMIZER: pct
TRAIN:
  l2: 1e-4
  learning_rate: 0.0001

AUG:
  NAME: cutmix_r
  BETA: 1.
  PROB: 0.5
