DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_c
  EXP_ID: c_robustnet2_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: robustnet2
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
